version: '1'

services:
  react-app:
    image: proven24/nimblefrontendtest:v1.9
    ports:
      - "3000:5173"
    depends_on:
      - fastapi-app

  fastapi-app:
    image: proven24/nimblebackendtest:v1.7
    ports:
      - "8000:7000"
    depends_on:
      - mysql-db

  mysql-db:
    image: proven24/databasetest:v1.0
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx!QAZ@WSX
      MYSQL_DATABASE: academicAlly
      MYSQL_USER: test1234
      MYSQL_PASSWORD: academicA!!y24
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
      - database-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  database-data: